### ISSUE TITLE
warning thrown during installation

### ISSUE THREAD

**Issue by osher** [chrisa/node-dtrace-provider#81]
The following warning is thrown every time I run npm install - even if the package is already installed:

```
(node:16136) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> dtrace-provider@0.6.0 install C:\ws\nodejs\my-app\node_modules\dtrace-provider
> node scripts/install.js
```

FYI

**Comment by davepacheco** [comment]
Which version of Node and NPM are you seeing this with?

**Comment by osher** [comment]
I can't say for sure, it's been a long way lately with node versions.
I was using many node versions: 0.12.7, 4.6.1, 6.3.1, 6.5.0, 6.8.0, 6.9.1 - and their matching npm.
(using nodist)

We currently moved to 6.9.1 and in this version the warning is not observed
I'm afraid I can't tell you when it stopped... 😛

**Comment by melloc** [comment]
Since the warning message came before the `dtrace-provider@0.6.0` line, I believe that the warning was due to something else, as any installation issues would have come after the `node scripts/install.js` output line.

Looking at isaacs/node-graceful-fs#66, it seems that npm itself uses `graceful-fs`, and that some versions of npm depended on the older version of the package that triggered the warning, so it seems likely that that was the issue here.
